version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27010:27010

  fastapi:
    build: .
    ports:
      - 4850:4850
    depends_on:
      - db
  seeder:
    build: ./seeder
    depends_on:
      - db
